#!/bin/bash

# Convert the MERIT .vrt to .tif

# modules
#module load lib/gdal/3.9.2

# ---------------------------------
# Specify settings
# ---------------------------------

# --- Location of source data

dest_line=$(grep -m 1 "^parameter_dem_unpack_path" ../../../0_control_files/control_active.txt)
data_path=$(echo ${dest_line##*|})
data_path=$(echo ${data_path%%#*})
data_path=$(echo "$data_path" | xargs)

if [ "$data_path" = "default" ]; then

    root_line=$(grep -m 1 "^root_path" ../../../0_control_files/control_active.txt)
    root_path=$(echo ${root_line##*|})
    root_path=$(echo ${root_path%%#*})
    root_path=$(echo "$root_path" | xargs)

    domain_line=$(grep -m 1 "^domain_name" ../../../0_control_files/control_active.txt)
    domain_name=$(echo ${domain_line##*|})
    domain_name=$(echo ${domain_name%%#*})
    domain_name=$(echo "$domain_name" | xargs)

    data_path="${root_path}/domain_${domain_name}/parameters/dem/2_MERIT_hydro_unpacked_data"
fi

# --- Location of source VRT

dest_line=$(grep -m 1 "^parameter_dem_vrt2_path" ../../../0_control_files/control_active.txt)
source_path=$(echo ${dest_line##*|})
source_path=$(echo ${source_path%%#*})
source_path=$(echo "$source_path" | xargs)

if [ "$source_path" = "default" ]; then

    root_line=$(grep -m 1 "^root_path" ../../../0_control_files/control_active.txt)
    root_path=$(echo ${root_line##*|})
    root_path=$(echo ${root_path%%#*})
    root_path=$(echo "$root_path" | xargs)

    domain_line=$(grep -m 1 "^domain_name" ../../../0_control_files/control_active.txt)
    domain_name=$(echo ${domain_line##*|})
    domain_name=$(echo ${domain_name%%#*})
    domain_name=$(echo "$domain_name" | xargs)

    source_path="${root_path}/domain_${domain_name}/parameters/dem/4_domain_vrt"
fi

# --- Location where converted data needs to go

dest_line=$(grep -m 1 "^parameter_dem_tif_path" ../../../0_control_files/control_active.txt)
dest_path=$(echo ${dest_line##*|})
dest_path=$(echo ${dest_path%%#*})
dest_path=$(echo "$dest_path" | xargs)

if [ "$dest_path" = "default" ]; then

    root_line=$(grep -m 1 "^root_path" ../../../0_control_files/control_active.txt)
    root_path=$(echo ${root_line##*|})
    root_path=$(echo ${root_path%%#*})
    root_path=$(echo "$root_path" | xargs)

    domain_line=$(grep -m 1 "^domain_name" ../../../0_control_files/control_active.txt)
    domain_name=$(echo ${domain_line##*|})
    domain_name=$(echo ${domain_name%%#*})
    domain_name=$(echo "$domain_name" | xargs)

    dest_path="${root_path}/domain_${domain_name}/parameters/dem/5_elevation"
fi

mkdir -p "$dest_path"

# --- Filenames

vrt_file=$(ls "$source_path"/*.vrt)

name_line=$(grep -m 1 "^parameter_dem_tif_name" ../../../0_control_files/control_active.txt)
dest_name=$(echo ${name_line##*|})
dest_name=$(echo ${dest_name%%#*})
dest_name=$(echo "$dest_name" | xargs)

tif_file="${dest_path}/${dest_name}"

# --------------------------------------------------------------------------
# Check if BIGTIFF is needed
# --------------------------------------------------------------------------

fold_size=($(du -s "$data_path"))

if ((fold_size > 4000000)); then
    bigtiff_flag='YES'
else
    bigtiff_flag='NO'
fi

# ---------------------------------
# Create .tif file
# ---------------------------------

gdal_translate \
    -co COMPRESS="DEFLATE" \
    -co BIGTIFF="$bigtiff_flag" \
    "$vrt_file" \
    "$tif_file"

# ---------------------------------
# Code provenance
# ---------------------------------

log_path="${dest_path}/_workflow_log"
mkdir -p "$log_path"

today=$(date '+%F')
log_file="${today}_compile_log.txt"

this_file='convert_vrt_to_tif.sh'

echo "Log generated by ${this_file} on $(date '+%F %H:%M:%S')" > "$log_path/$log_file"
echo 'Converted MERIT .vrt into .tif.' >> "$log_path/$log_file"

cp "$this_file" "$log_path"