#!/bin/bash

# Unpack MERIT-Hydro elevation archives for one CWARHM domain.
#
# The domain-specific control file is supplied explicitly.
# No shared control_active.txt is used.
#
# Usage:
#
# bash unpack_merit_hydro_dem.sh /path/to/control_DOMAIN.txt
#
# Example:
#
# bash unpack_merit_hydro_dem.sh \
# /work/comphyd_lab/users/arman.haddadchi/NWAM/CWARHM_multibasin/0_control_files/control_MERIT_717.txt

set -euo pipefail


# ============================================================
# CONTROL FILE
# ============================================================

if [ "$#" -ne 1 ]; then
    echo "Usage:"
    echo "bash unpack_merit_hydro_dem.sh /path/to/control_DOMAIN.txt"
    exit 1
fi

CONTROL=$(realpath "$1")

if [ ! -f "$CONTROL" ]; then
    echo "ERROR: Control file not found:"
    echo "$CONTROL"
    exit 1
fi


# ============================================================
# CONTROL-FILE FUNCTION
# ============================================================

read_control() {

    local setting="$1"
    local value

    value=$(
        awk -F'|' -v key="$setting" '
        /^[[:space:]]*#/ { next }
        {
            left=$1
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", left)

            if (left == key) {
                right=$2
                sub(/#.*/, "", right)
                gsub(/^[[:space:]]+|[[:space:]]+$/, "", right)
                print right
                exit
            }
        }
        ' "$CONTROL"
    )

    if [ -z "$value" ]; then
        echo "ERROR: Setting not found or empty: $setting" >&2
        exit 1
    fi

    printf '%s\n' "$value"
}


# ============================================================
# DOMAIN SETTINGS
# ============================================================

root_path=$(read_control "root_path")
domain_name=$(read_control "domain_name")


# ============================================================
# SOURCE PATH
# ============================================================

source_path=$(read_control "parameter_dem_raw_path")

if [ "$source_path" = "default" ]; then

    source_path="${root_path}/domain_${domain_name}/parameters/dem/1_MERIT_hydro_raw_data"

fi


# ============================================================
# DESTINATION PATH
# ============================================================

dest_path=$(read_control "parameter_dem_unpack_path")

if [ "$dest_path" = "default" ]; then

    dest_path="${root_path}/domain_${domain_name}/parameters/dem/2_MERIT_hydro_unpacked_data"

fi


# ============================================================
# VALIDATE PATHS
# ============================================================

if [ ! -d "$source_path" ]; then
    echo "ERROR: MERIT-Hydro raw-data directory not found:"
    echo "$source_path"
    exit 1
fi

mkdir -p "$dest_path"


# ============================================================
# REPORT
# ============================================================

echo
echo "======================================================================"
echo "UNPACK MERIT-HYDRO ELEVATION"
echo "======================================================================"
echo
echo "Domain      : $domain_name"
echo "Control file: $CONTROL"
echo "Source      : $source_path"
echo "Destination : $dest_path"
echo


# ============================================================
# FIND INPUT ARCHIVES
# ============================================================

shopt -s nullglob

tar_files=(
    "$source_path"/*.tar
)

shopt -u nullglob

if [ "${#tar_files[@]}" -eq 0 ]; then
    echo "ERROR: No MERIT-Hydro .tar files found in:"
    echo "$source_path"
    exit 1
fi

echo "MERIT-Hydro archives found: ${#tar_files[@]}"
echo


# ============================================================
# UNPACK DATA
# ============================================================

unpacked_count=0

for file in "${tar_files[@]}"; do

    echo "Unpacking:"
    echo "  $file"

    tar -xf "$file" \
        -C "$dest_path"

    unpacked_count=$((unpacked_count + 1))

done


# ============================================================
# VERIFY OUTPUT
# ============================================================

tif_count=$(
    find "$dest_path" \
        -type f \
        -name "*.tif" \
        | wc -l
)

if [ "$tif_count" -eq 0 ]; then
    echo
    echo "ERROR: No GeoTIFF files were found after extraction:"
    echo "$dest_path"
    exit 1
fi


# ============================================================
# WORKFLOW LOG
# ============================================================

log_path="${dest_path}/_workflow_log"

mkdir -p "$log_path"

timestamp=$(date '+%Y%m%d_%H%M%S')

log_file="${log_path}/${timestamp}_unpack_merit_hydro_dem.txt"

this_file=$(basename "$0")

cp "$0" \
    "$log_path/$this_file"

cp "$CONTROL" \
    "$log_path/$(basename "$CONTROL")"


{
    echo "Log generated by ${this_file} on $(date '+%F %H:%M:%S')"
    echo "Domain: ${domain_name}"
    echo "Control file: ${CONTROL}"
    echo "Source directory: ${source_path}"
    echo "Destination directory: ${dest_path}"
    echo "Archives unpacked: ${unpacked_count}"
    echo "GeoTIFF files found: ${tif_count}"
} > "$log_file"


# ============================================================
# SUMMARY
# ============================================================

echo
echo "======================================================================"
echo "MERIT-HYDRO UNPACK COMPLETED"
echo "======================================================================"
echo "Domain            : $domain_name"
echo "Archives unpacked : $unpacked_count"
echo "GeoTIFF files     : $tif_count"
echo "Output directory  : $dest_path"
echo "Workflow log      : $log_file"