#!/bin/bash

# Make a virtual dataset (VRT) for MERIT Hydro elevation data.

# Load GDAL
#module load lib/gdal/3.9.2

# ---------------------------------
# Specify settings
# ---------------------------------

# --- Location of unpacked MERIT Hydro data

dest_line=$(grep -m 1 "^parameter_dem_unpack_path" ../../../0_control_files/control_active.txt)
source_path=$(echo ${dest_line##*|})
source_path=$(echo ${source_path%%#*})
source_path=$(echo "$source_path" | xargs)

if [ "$source_path" = "default" ]; then

    root_line=$(grep -m 1 "^root_path" ../../../0_control_files/control_active.txt)
    root_path=$(echo ${root_line##*|})
    root_path=$(echo ${root_path%%#*})
    root_path=$(echo "$root_path" | xargs)

    domain_line=$(grep -m 1 "^domain_name" ../../../0_control_files/control_active.txt)
    domain_name=$(echo ${domain_line##*|})
    domain_name=$(echo ${domain_name%%#*})
    domain_name=$(echo "$domain_name" | xargs)

    source_path="${root_path}/domain_${domain_name}/parameters/dem/2_MERIT_hydro_unpacked_data"

fi

# --- Location where VRT data will go

dest_line=$(grep -m 1 "^parameter_dem_vrt1_path" ../../../0_control_files/control_active.txt)
dest_path=$(echo ${dest_line##*|})
dest_path=$(echo ${dest_path%%#*})
dest_path=$(echo "$dest_path" | xargs)

if [ "$dest_path" = "default" ]; then

    root_line=$(grep -m 1 "^root_path" ../../../0_control_files/control_active.txt)
    root_path=$(echo ${root_line##*|})
    root_path=$(echo ${root_path%%#*})
    root_path=$(echo "$root_path" | xargs)

    domain_line=$(grep -m 1 "^domain_name" ../../../0_control_files/control_active.txt)
    domain_name=$(echo ${domain_line##*|})
    domain_name=$(echo ${domain_name%%#*})
    domain_name=$(echo "$domain_name" | xargs)

    dest_path="${root_path}/domain_${domain_name}/parameters/dem/3_vrt"

fi

# Make destination directory
mkdir -p "${dest_path}/filelists"

# ---------------------------------
# Make the VRT
# ---------------------------------

OUTTXT="${dest_path}/filelists/MERIT_Hydro_dem_filelist.txt"
OUTVRT="${dest_path}/MERIT_Hydro_dem.vrt"

# Find all unpacked MERIT Hydro GeoTIFF files
find "$source_path" -name "*.tif" > "$OUTTXT"

# Build VRT
gdalbuildvrt "$OUTVRT" \
    -input_file_list "$OUTTXT" \
    -resolution highest

# ---------------------------------
# Code provenance
# ---------------------------------

log_path="${dest_path}/_workflow_log"
mkdir -p "$log_path"

today=$(date '+%F')
log_file="${today}_compile_log.txt"

this_file='make_merit_dem_vrt.sh'

echo "Log generated by ${this_file} on $(date '+%F %H:%M:%S')" > "$log_path/$log_file"
echo 'Created Virtual Dataset from MERIT .tif data.' >> "$log_path/$log_file"

cp "$this_file" "$log_path"